### PR TITLE
Update react version

### PR DESCRIPTION
**Pull request by mdedys**
Update the versions of react. I am using activity-viewer in a project my team is working on and we use react 15. In order to update activity-viewer I needed to update this library, and react-vui-fileviewer as well. Those PRs will be created shortly.

### CODE REVIEW

**Comment by CodeBaboon** [comment]
If we are moving this project to ES2015 we may want to do a follow-up PR to change our `var`s to `const`s and `let`s.

**Comment by mdedys** [comment]
That is a good idea. I was thinking of moving to vars -> const and moving to classes for the components but held back on those changes as I didn't have the time to make sure everything was tested. I will maybe try and get this done later this week or next week if I  get time.

**Comment by mdedys** [comment]
These changes will need a major version bump in order to not break existing libraries relying on this.

**Comment by mdedys** [comment]
Can this be merged, version incremented and tagged when the changes are approved. I don't have access to this repo.

**Comment by CodeBaboon** [comment]
LGTM

**Pull request merged**
