### PR TITLE
DE23815

### PR DESCRIPTION
**Pull request by klhuff**
Set allowFullScreen on the iframe for ASV. This allows embeds, such as youtube iframes to go full screen.

### CODE REVIEW

**Comment by Surekh** [comment]
LGTM! But I will let @CodeBaboon have the final say.

**Comment by CodeBaboon** [comment]
Code LGTM. My only concern would be if this allows for content to 'break' the ASV experience by full-screening their content. Is @GianD2L aware of this behaviour modification and had a chance to think through any possible ramifications?

**Comment by klhuff** [comment]
If it helps at all, we do this with the iFrame (ie. it has allowfullscreen property) in the regular content tool already. As far as content (and ASV) is concerned, I think it's ok to trust that instructors will make the kinds of content they want to make (and we allow things like javascript, etc. to be loaded within the content iframe).

**Comment by CodeBaboon** [comment]
Yeah I'm not opposed to it, I just want to make sure we aren't overlooking any gotchas. The ASV experience is intended to be fairly 'prescribed' and guided, and this does allow for that experience to be modified in a new way.

**Pull request merged**
